# Homebrew formula for Haven — prebuilt binary, no Rust toolchain needed.
# Copy into the tap repo (nibbletech-labs/homebrew-tap) as Formula/haven.rb.
# Generated by .github/workflows/release.yml for v0.1.1.
class Haven < Formula
  desc "Local-first work-graph store for humans and AI agents"
  homepage "https://github.com/nibbletech-labs/haven"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.1/haven-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "3b31eab9d869c47548a8fca33ec7a54de3813e9fb5f2e870c720a8f727fcbf0c"
    end
    on_intel do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.1/haven-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "89795089fe5745aa849f9c545c4e4539100ac82e35ba1a8478350b7c01e9b9fc"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.1/haven-0.1.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "444c122884dd6f11fb1be77d8b2e23ff2a44f567d9a29f65b4ac7ad55c4457f5"
    end
    on_intel do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.1/haven-0.1.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "76cf8d743b48de6744813f159141be78dec00e92fc788bc4bcdd61ea38250750"
    end
  end

  def install
    bin.install "haven"
  end

  def caveats
    <<~CAVEAT
      Wire the MCP server + Claude skill (idempotent):
        haven setup
      Then check the install:
        haven doctor
    CAVEAT
  end

  test do
    assert_match "haven", shell_output("#{bin}/haven --version")
  end
end
