# Homebrew formula for Haven — prebuilt binary, no Rust toolchain needed.
# Generated by .github/workflows/release.yml for v0.1.4.
class Haven < Formula
  desc "Local-first work-graph store for humans and AI agents"
  homepage "https://github.com/nibbletech-labs/haven"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.4/haven-0.1.4-aarch64-apple-darwin.tar.gz"
      sha256 "2e275c6f5e65c1a63b4a7126ab157d39876b78982c1dff02f0193904ebeb6a0e"
    end
    on_intel do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.4/haven-0.1.4-x86_64-apple-darwin.tar.gz"
      sha256 "d37ff49cff4c31838915b0220548c9f28354b00252751b4f0436d380b2ecf3f1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.4/haven-0.1.4-aarch64-unknown-linux-musl.tar.gz"
      sha256 "d7a490216a2e1721177fc0c18bc50946b994cc96b2d92cffa4f8d999917fda51"
    end
    on_intel do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.4/haven-0.1.4-x86_64-unknown-linux-musl.tar.gz"
      sha256 "78cc230c7e855c8a1d092b129f43f5db123b749df47d735ba0c7dc3c605614e2"
    end
  end

  def install
    bin.install "haven"
  end

  def caveats
    <<~CAVEAT
      Wire the MCP server + skills and create/select a first project:
        haven setup --project-key my-work --project-title "My Work" --prefix MW
      Then add an item and check the install:
        haven item add "First item"
        haven doctor
    CAVEAT
  end

  test do
    assert_match "haven", shell_output("#{bin}/haven --version")
  end
end
