# Homebrew formula for Haven — prebuilt binary, no Rust toolchain needed.
# Copy into the tap repo (nibbletech-labs/homebrew-tap) as Formula/haven.rb.
# Generated by .github/workflows/release.yml for v0.1.7.
class Haven < Formula
  desc "Local-first work-graph store for humans and AI agents"
  homepage "https://github.com/nibbletech-labs/haven"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.7/haven-0.1.7-aarch64-apple-darwin.tar.gz"
      sha256 "dd6145582b9b3b811853437b1dfe877ef63ef951491faf8a50ec543d1470deb8"
    end
    on_intel do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.7/haven-0.1.7-x86_64-apple-darwin.tar.gz"
      sha256 "aeba2e34144c3308802b179ef0a54c9778aa369955fd9da81e2f46e9275b7d5d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.7/haven-0.1.7-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4c7b92361a0e0edc724869898e72d11fedec37243fe0026d51b7925235b84e6b"
    end
    on_intel do
      url "https://github.com/nibbletech-labs/haven/releases/download/v0.1.7/haven-0.1.7-x86_64-unknown-linux-musl.tar.gz"
      sha256 "890ae52a095bb1e71709313e72b3d750e732e47627e3512b0768f2077635c074"
    end
  end

  def install
    bin.install "haven"
  end

  def caveats
    <<~CAVEAT
      Wire the MCP server + skills and create/select a first project:
        haven setup --project-key my-work --project-title "My Work" --prefix MW
      Then add an item and check the install:
        haven item add "First item"
        haven doctor
    CAVEAT
  end

  test do
    assert_match "haven", shell_output("#{bin}/haven --version")
  end
end
